# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('standard', models.CharField(max_length=2)),
            ],
        ),
    ]
