# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classTestInfo',
            fields=[
                ('dct_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('standard', models.CharField(max_length=2)),
                ('main_module', models.CharField(max_length=50)),
                ('sub_module', models.CharField(max_length=50)),
                ('subjective', models.IntegerField()),
                ('obejective', models.IntegerField()),
                ('testDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='studentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctSubjective', models.IntegerField()),
                ('wrongSubjective', models.IntegerField()),
                ('correctObjective', models.IntegerField()),
                ('wrongObjective', models.IntegerField()),
                ('total', models.IntegerField()),
                ('DCT_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dct.classTestInfo')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dct.student')),
            ],
        ),
    ]
