# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0002_classtestinfo_studentmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
