# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0003_auto_20181126_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='total',
            field=models.DecimalField(decimal_places=2, default='000.00', max_digits=6),
        ),
    ]
