# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0005_auto_20181128_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
