# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0007_auto_20181129_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtestinfo',
            old_name='obejective',
            new_name='obejective_total',
        ),
        migrations.RenameField(
            model_name='classtestinfo',
            old_name='subjective',
            new_name='subjective_total',
        ),
        migrations.AlterField(
            model_name='classtestinfo',
            name='dct_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classtestinfo',
            name='standard',
            field=models.CharField(max_length=5),
        ),
    ]
