# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0008_auto_20181129_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtestinfo',
            old_name='obejective_total',
            new_name='objective_total',
        ),
    ]
