# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0009_auto_20181129_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtestinfo',
            name='testDate',
            field=models.CharField(max_length=10),
        ),
    ]
