# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0010_auto_20181129_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='total',
            new_name='obj_total',
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
