# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0011_auto_20181129_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='DCT_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dct.classTestInfo'),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='Student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dct.student'),
        ),
    ]
