# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0012_auto_20181129_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='DCT_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='Student_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
